logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: ERROR
      apache.kafka: WARN

kafka:
  bootstrap-servers: localhost:9092

  topics:
    sensors: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1

  consumer:
    group-id: telemetry-aggregator-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: ru.yandex.practicum.deserializer.SensorEventDeserializer
    auto-offset-reset: earliest

  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: ru.yandex.practicum.serializer.GeneralAvroSerializer